#!/bin/ash

echo Installing Lise-yun

echo Installing node binaries
cp ./bin/* /usr/bin/
echo Installing libraries
mkdir -p /usr/lib/node_modules
cp -r ./lib/serialport /usr/lib/node_modules/serialport

echo Adding server to startup-routine
echo /usr/bin/node $(pwd)/server/index.js > /etc/rc.local

echo Disabling bridge
echo "::sysinit:/etc/init.d/rcS S boot
::shutdown:/etc/init.d/rcS K shutdown
#ttyATH0::askfirst:/bin/ash --login" > /etc/inittab

echo *** Installation succesful. Server will be available at http://arduino.local:3000/ ***
echo *** Rebooting.. please wait. ***

reboot