export const CONTROLPANEL_START = 'CONTROLPANEL_START';
export const CONTROLPANEL_STOP = 'CONTROLPANEL_STOP';

export const PAGE_SETPATH = 'PAGE_SETPATH';

export const NOTIFICATIONS_SHOWNOTIFICATION = 'NOTIFICATIONS_SHOWNOTIFICATION';
export const NOTIFICATIONS_HIDENOTIFICATION = 'NOTIFICATIONS_HIDENOTIFICATION';

export const PORTS_UPDATEPORTS = 'PORTS_UPDATEPORTS';
export const PORTS_SELECTPORT = 'PORTS_SELECTPORT';
export const PORTS_CONNECTIONSTATUS = 'PORTS_CONNECTIONSTATUS';
export const PORTS_CONNECTIONINFO = 'PORTS_CONNECTIONINFO';