export const CONTROLPANEL_START = 'CONTROLPANEL_START';
export const CONTROLPANEL_STOP = 'CONTROLPANEL_STOP';

export const PAGE_SETPATH = 'PAGE_SETPATH';

export const NOTIFICATIONS_SHOWNOTIFICATION = 'NOTIFICATIONS_SHOWNOTIFICATION';
export const NOTIFICATIONS_HIDENOTIFICATION = 'NOTIFICATIONS_HIDENOTIFICATION';

export const PORTS_UPDATEPORTS = 'PORTS_UPDATEPORTS';
export const PORTS_SELECTPORT = 'PORTS_SELECTPORT';
export const PORTS_CONNECTIONSTATUS = 'PORTS_CONNECTIONSTATUS';
export const PORTS_CONNECTIONINFO = 'PORTS_CONNECTIONINFO';

export const SKETCH_GET_SAMPLERATE = 'SKETCH_GET_SAMPLERATE';
export const SKETCH_POST_SAMPLERATE = 'SKETCH_POST_SAMPLERATE';
export const SKETCH_UPDATE_SAMPLERATE = 'SKETCH_UPDATE_SAMPLERATE';
export const SKETCH_UPDATE_GAIN = 'SKETCH_UPDATE_GAIN';
export const SKETCH_SETVERSION = 'SKETCH_SETVERSION';
export const SKETCH_SET_STATUS = 'SKETCH_SET_STATUS';

export const OS_GET_OS = 'OS_GET_OS';
export const OS_SET_OS = 'OS_SET_OS';

export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_HIDE = 'MODAL_HIDE';
export const MODAL_SET_CONTENT = 'MODAL_SET_CONTENT';